### ISSUE TITLE
Get original tests working

### ISSUE THREAD

**Issue by dromer** [Wasted-Audio/hvcc#10] opened 2021-04-01 23:06 UTC
Not all of them will be functional (like `test_uploader.py`), but at least the basic ones would be nice to have.

Some work has been done in https://github.com/dromer/hvcc/pull/7 to achieve this.

**Comment by shakfu** [comment] 2021-06-14 05:11
As you no doubt know, the original tests seem to use external code which was not checked into the `hvcc` repo. That's not to say they don't work, it's just they seem to be written with a different setup.

It probably makes sense to rewrite them (while keeping the original tests intact for reference until full coverage is achieved).

In my fork, I have done partially tested the `signal` part the test-suite which tests compilation via hvcc then via c and cpp to an executable which can generate `.wav` files. The test runs fine and the `.wav` files are generate and played using `sox`.

Your python3 translation seems to work fine so far (-:

Check it out here: https://github.com/shakfu/hvcc/tree/develop/tests_new/signal

**Comment by shakfu** [comment] 2022-01-26 21:37
Amazing progress @dromer 👍

**Comment by dromer** [comment] 2022-01-26 22:28
thnx @shakfu ! did you manage to continue any work on the tests? I do want to get back to them at some point. definitely before getting to a `1.0` state.

**Comment by shakfu** [comment] 2022-01-27 14:06
Hi @dromer no work beyond what I did earlier, but given your extensive changes, I'll see if I can revisit the tests again against the new changes.

**Comment by dromer** [comment] 2022-01-27 15:57
The changes are pretty much only to the generators and midi sections.

I think for the tests it's best if they focus on core DSP functionality (which afaik most of them do anyway).
In the coming weeks I want to do another dive into this. Will hopefully help me understand some of the architecture a little better as well :)

For the generators I'm thinking of creating separate repositories with examples and CI to confirm (crossplat) builds.

**Comment by dromer** [comment] 2022-01-29 10:40
Did a bit more work on this. Branch is updated and the CI runs the plain `signal` tests for py38.

Will try and get the other tests running as well, but slowly some progress :)

**Comment by dromer** [comment] 2022-01-29 12:16
`tests/test_control.py` now mostly works! only issue is with `test_select` and it seems that `[symbol str(` isn't properly recognized (yet).

**Comment by shakfu** [comment] 2022-01-29 13:34
Are you using `nose` (no longer maintained), or `nose2` or `pytest` for tests? I've tried all of the above from the root and the the `tests` director on your `feature/fix-tests` branch and I'm not able to get any tests to run successfully.

**Comment by dromer** [comment] 2022-01-29 13:37
Just `pip install tox` and run `tox` then it'll go over the entire (enabled) test-suite.

**Comment by shakfu** [comment] 2022-01-29 13:42
No Worries. I found your `tox.ini`. It's `pytest` after all: `python3 -m pytest --ignore=examples`

**Comment by shakfu** [comment] 2022-01-29 13:50
Results:

```python3

$ python3 -m pytest --ignore=examples
============================= test session starts ==============================
platform darwin -- Python 3.9.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: $HOME/code/hvcc
plugins: cov-3.0.0
collected 90 items / 3 skipped / 87 selected

tests/test_control.py .................................................. [ 55%]
...............s......................                                   [ 97%]
tests/test_signal.py FF                                                  [100%]

=================================== FAILURES ===================================
________________________ TestPdSignalPatches.test_line _________________________

self = <test_signal.TestPdSignalPatches testMethod=test_line>

    def test_line(self):
>       self._test_signal_patch("test-line.pd")

tests/test_signal.py:154:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_signal.py:140: in _test_signal_patch
    self._compare_wave_output(out_dir, source_files, golden_path, "HV_SIMD_NONE")
tests/test_signal.py:86: in _compare_wave_output
    [g_fs, golden] = wavfile.read(golden_path)
/usr/local/lib/python3.9/site-packages/scipy/io/wavfile.py:650: in read
    file_size, is_big_endian = _read_riff_chunk(fid)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fid = <_io.BufferedReader name='/Users/sa/Downloads/projects/hvcc/tests/pd/signal/test-line.golden.wav'>

    def _read_riff_chunk(fid):
        str1 = fid.read(4)  # File signature
        if str1 == b'RIFF':
            is_big_endian = False
            fmt = '<I'
        elif str1 == b'RIFX':
            is_big_endian = True
            fmt = '>I'
        else:
            # There are also .wav files with "FFIR" or "XFIR" signatures?
>           raise ValueError(f"File format {repr(str1)} not understood. Only "
                             "'RIFF' and 'RIFX' supported.")
E           ValueError: File format b'vers' not understood. Only 'RIFF' and 'RIFX' supported.

/usr/local/lib/python3.9/site-packages/scipy/io/wavfile.py:521: ValueError
___________________ TestPdSignalPatches.test_phasor_control ____________________

self = <test_signal.TestPdSignalPatches testMethod=test_phasor_control>

    def test_phasor_control(self):
>       self._test_signal_patch("test-phasor-control.pd")

tests/test_signal.py:157:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_signal.py:140: in _test_signal_patch
    self._compare_wave_output(out_dir, source_files, golden_path, "HV_SIMD_NONE")
tests/test_signal.py:86: in _compare_wave_output
    [g_fs, golden] = wavfile.read(golden_path)
/usr/local/lib/python3.9/site-packages/scipy/io/wavfile.py:650: in read
    file_size, is_big_endian = _read_riff_chunk(fid)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fid = <_io.BufferedReader name='/Users/sa/Downloads/projects/hvcc/tests/pd/signal/test-phasor-control.golden.wav'>

    def _read_riff_chunk(fid):
        str1 = fid.read(4)  # File signature
        if str1 == b'RIFF':
            is_big_endian = False
            fmt = '<I'
        elif str1 == b'RIFX':
            is_big_endian = True
            fmt = '>I'
        else:
            # There are also .wav files with "FFIR" or "XFIR" signatures?
>           raise ValueError(f"File format {repr(str1)} not understood. Only "
                             "'RIFF' and 'RIFX' supported.")
E           ValueError: File format b'vers' not understood. Only 'RIFF' and 'RIFX' supported.

/usr/local/lib/python3.9/site-packages/scipy/io/wavfile.py:521: ValueError
=========================== short test summary info ============================
FAILED tests/test_signal.py::TestPdSignalPatches::test_line - ValueError: Fil...
FAILED tests/test_signal.py::TestPdSignalPatches::test_phasor_control - Value...
============= 2 failed, 87 passed, 4 skipped in 125.93s (0:02:05) ==============
```

**Comment by dromer** [comment] 2022-01-29 13:51
Oh, you need to installl `git-lfs` and use `git lfs pull` to retrieve those assets.

**Comment by shakfu** [comment] 2022-01-29 13:54
Incidentally, I had to `pip install importlib-resources` on python3.9 for the above to run.

**Comment by dromer** [comment] 2022-01-29 13:57
My local pyenv is still `3.8` so I've been testing on that (so far only enabled the tests for `py38` also to keep things fast). Will try other python versions later.

Will see if I can confirm that dependency and add it to the `requirements-test.txt` file :)

**Comment by shakfu** [comment] 2022-01-29 14:12
Ok, after installing `git-lfs` via `brew install git-lfs`:

```python3
$ python3 -m pytest --ignore=examples
============================= test session starts ==============================
platform darwin -- Python 3.9.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: #HOME/code/hvcc
plugins: cov-3.0.0
collected 90 items / 3 skipped / 87 selected

tests/test_control.py .................................................. [ 55%]
...............s......................                                   [ 97%]
tests/test_signal.py ..                                                  [100%]

================== 89 passed, 4 skipped in 119.16s (0:01:59) ===================

```

**Comment by shakfu** [comment] 2022-01-29 15:13
I see that the `test_signals` tests are only two methods:

```python3
    def test_line(self):
        self._test_signal_patch("test-line.pd")

    def test_phasor_control(self):
        self._test_signal_patch("test-phasor-control.pd")
```
Presumably from the example of `test_control` that to make progress and increase coverage of signal-tests, one has to add methods to `test_signal.py` as above and `generate golden files for signal tests`.

**Comment by shakfu** [comment] 2022-01-29 16:16
Incidentally what have you been using to generate the `golden.wav` files for each test. If I run the following:

```python3
$python3 tests/test_signal.py tests/pd/signal/test-line.pd
Traceback (most recent call last):
  File "$HOME/code/hvcc/tests/test_signal.py", line 253, in <module>
    main()
  File "$HOME/code/hvcc/tests/test_signal.py", line 235, in main
    out_dir = TestPdSignalPatches._run_hvcc(args.pd_path)
  File "$HOME/code/hvcc/tests/test_signal.py", line 108, in _run_hvcc
    hvcc_results = hvcc.compile_dataflow(pd_path, out_dir)
AttributeError: module 'hvcc' has no attribute 'compile_dataflow'
vole:hvcc sa$ python3 tests/test_signal.py tests/pd/signal/test-line.pd
Traceback (most recent call last):
  File "$HOME/code/hvcc/tests/test_signal.py", line 28, in <module>
    import hvcc
ModuleNotFoundError: No module named 'hvcc'
vole:hvcc sa$ python3 tests/test_signal.py tests/pd/signal/test-line.pd
Traceback (most recent call last):
  File "$HOME/code/hvcc/tests/test_signal.py", line 253, in <module>
    main()
  File "$HOME/code/hvcc/tests/test_signal.py", line 235, in main
    out_dir = TestPdSignalPatches._run_hvcc(args.pd_path)
  File "$HOME/code/hvcc/tests/test_signal.py", line 108, in _run_hvcc
    hvcc_results = hvcc.compile_dataflow(pd_path, out_dir)
AttributeError: module 'hvcc' has no attribute 'compile_dataflow'
vole:hvcc sa$ python3 tests/test_signal.py tests/pd/signal/test-line.pd
Traceback (most recent call last):
  File "$HOME/code/hvcc/tests/test_signal.py", line 253, in <module>
    main()
  File "$HOME/code/hvcc/tests/test_signal.py", line 235, in main
    out_dir = TestPdSignalPatches._run_hvcc(args.pd_path)
  File "$HOME/code/hvcc/tests/test_signal.py", line 108, in _run_hvcc
    hvcc_results = hvcc.compile_dataflow(pd_path, out_dir)
AttributeError: module 'hvcc' has no attribute 'compile_dataflow'
```

**Comment by dromer** [comment] 2022-01-29 18:24
Btw the point is to have the `golden` files be created by Pd, otherwise there is no point in comparing the output with hvcc.

I'll ask Joe about how they created these files originally.

**Comment by shakfu** [comment] 2022-01-29 22:02
> Btw the point is to have the `golden` files be created by Pd, otherwise there is no point in comparing the output with hvcc.

Yes, I was aware of this, thanks.

> I'll ask Joe about how they created these files originally.

That would be great. 

I assumed that the command-line infrastructure in each file such as `tests/test_control.py` and `tests/test_signal.py`  was intended to generate those `golden wav files`. See for example the following main` function in `tests/test_signal.py`:

```python3
def main():
    parser = argparse.ArgumentParser(
        description="A script used to generate golden files for signal tests.")
    parser.add_argument(
        "pd_path",
        help="A Pd patch to render to WAV.")
    parser.add_argument(
        "--simd",
        default="HV_SIMD_NONE",
        help="Possible values are 'HV_SIMD_NONE', 'HV_SIMD_SSE', 'HV_SIMD_SSE_FMA', 'HV_SIMD_AVX', or HV_SIMD_NEON.")
    parser.add_argument(
        "--samplerate", "-r",
        type=int,
        default=48000,
        help="Defaults to 48000.")
    parser.add_argument(
        "--blocksize", "-b",
        type=int,
        default=480,
        help="Defaults to 480.")
    parser.add_argument(
        "--numblocks", "-n",
        type=int,
        default=100,
        help="Defaults to 100.")
    parser.add_argument(
        "--verbose", "-v",
        help="Show debugging information.",
        action="count")
    args = parser.parse_args()

    out_dir = TestPdSignalPatches._run_hvcc(args.pd_path)

    c_src_dir = os.path.join(out_dir, "c")
    c_sources = [os.path.join(c_src_dir, c) for c in os.listdir(c_src_dir) if c.endswith(".c")]

    wav_path = TestPdSignalPatches._compile_and_run(
        out_dir,
        c_sources,
        args.samplerate,
        args.blocksize,
        args.numblocks,
        flag=args.simd)

    if args.verbose:
        print(os.path.abspath(wav_path))
```

But I couldn't get this script to run as mentioned earlier from the root of the project file or from one level into the `tests` directory.

**Comment by dromer** [comment] 2022-01-29 23:37
For the script to work you need to have hvcc installed in your path, btw.

It runs for me, but I get other errors hehe:

```
hvcc/tests$ python test_signal.py pd/signal/test-line.pd 
make: *** No rule to make target 'build/c/HvMessageQueue.o', needed by 'main'.  Stop.
Traceback (most recent call last):
  File "test_signal.py", line 209, in <module>
    main()
  File "test_signal.py", line 196, in main
    wav_path = TestPdSignalPatches._compile_and_run(
  File "test_signal.py", line 65, in _compile_and_run
    subprocess.check_output(["make", "-C", os.path.dirname(makefile_path), "-j"])
  File "/home/dreamer/.pyenv/versions/3.8.7/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/dreamer/.pyenv/versions/3.8.7/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', '-C', 'build/c', '-j']' returned non-zero exit status 2.
```

Anyway this script is more meant for quick-n-dirty manual runs and to try different use flags.
Nearly all the generators and other modules in hvcc are also scripts you can manually run (although most of them I've never used like that).

**Comment by shakfu** [comment] 2022-01-31 20:12
As per a previous experiment, which still works, thankfully, try the following with the attached `tests_new.zip`:

1. unzip `tests_new.zip` and place the `tests_new` folder in the root of the repo so its path is `hvcc/tests_new`.
2. make a virtualenv: `virtualenv venv && source venv/bin/activate`
3. with the virtualenv active: 

```
pip install -r requirements.txt
pip install colorlog # to add some color to the log output
cd tests_new/signal
./build.py
```
The build.py script simply runs the Makefile on all `.pd`

 This should generate a bunch of wav files and in the `wavs` folder.

This test copies each pd file from `tests/pd/signal`, compiles it using `hvcc`, compiles the resultant cpp file, generates a wav file. This demonstrates that the issue is not with the `pd` files but with compilation machinery in `tests_signal.py`, etc  needs updating.

[tests_new.zip](https://github.com/Wasted-Audio/hvcc/files/7973780/tests_new.zip)

**Closed** 2022-02-05 16:16 UTC
Labels: help wanted
